add git_status
Signed-off-by: Anagnostakis Ioannis <elahistos@yahoo.gr>

diff --git a/home/bashrc b/home/bashrc
--- a/home/bashrc
+++ b/home/bashrc
@@ -59,7 +59,7 @@ alias sign_patch="git format-patch -1 HEAD"
 alias aplo_patch="git diff HEAD^ > file.patch"
 #alias sign="cat ~/GITHUB/Signed-off-by"
 alias man="man --html=firefox "
-alias topatch="cat ~/Templates/entoli-patch"
+alias topatch="echo 'diff -Naur file-original file-new > file.patch'"
 alias img2logo="cat ~/Templates/convert-images"
 alias img2gif="cat ~/Templates/img2gif"
 alias l6="/usr/bin/linguist6"
@@ -168,6 +168,7 @@ alias logs="sudo find /var/log -type f -exec file {} \; | grep 'text' | cut -d' 
 alias krnl="uname -r"
 alias cpu="grep 'cpu ' /proc/stat | awk '{usage=(\$2+\$4)*100/(\$2+\$4+\$5)} END {print usage}' | awk '{printf(\"%.1f\n\", \$1)}'"
 alias gitfix="git fetch &&  git reset --hard origin/main"
+
 
 # find deps for official slackware packages using salixos tools...
 dep() {
@@ -454,135 +455,98 @@ trim()
 
 function __setprompt
 {
-	local LAST_COMMAND=$? # Must come first!
+    local LAST_COMMAND=$? # Must come first!
 
-	# Define colors
-	local LIGHTGRAY="\033[0;37m"
-	local WHITE="\033[1;37m"
-	local BLACK="\033[0;30m"
-	local DARKGRAY="\033[1;30m"
-	local RED="\033[0;31m"
-	local LIGHTRED="\033[1;31m"
-	local GREEN="\033[0;32m"
-	local LIGHTGREEN="\033[1;32m"
-	local BROWN="\033[0;33m"
-	local YELLOW="\033[1;33m"
-	local BLUE="\033[0;34m"
-	local LIGHTBLUE="\033[1;34m"
-	local MAGENTA="\033[0;35m"
-	local LIGHTMAGENTA="\033[1;35m"
-	local CYAN="\033[0;36m"
-	local LIGHTCYAN="\033[1;36m"
-	local NOCOLOR="\033[0m"
-
-# Show error exit code if there is one
-	if [[ $LAST_COMMAND != 0 ]]; then
-		# PS1="\[${RED}\](\[${LIGHTRED}\]ERROR\[${RED}\])-(\[${LIGHTRED}\]Exit Code \[${WHITE}\]${LAST_COMMAND}\[${RED}\])-(\[${LIGHTRED}\]"
-		PS1="\[${DARKGRAY}\](\[${LIGHTRED}\]ERROR\[${DARKGRAY}\])-(\[${RED}\]Exit Code \[${LIGHTRED}\]${LAST_COMMAND}\[${DARKGRAY}\])-(\[${RED}\]"
-		if [[ $LAST_COMMAND == 1 ]]; then
-			PS1+="General error"
-		elif [ $LAST_COMMAND == 2 ]; then
-			PS1+="Missing keyword, command, or permission problem"
-		elif [ $LAST_COMMAND == 126 ]; then
-			PS1+="Permission problem or command is not an executable"
-		elif [ $LAST_COMMAND == 127 ]; then
-			PS1+="Command not found"
-		elif [ $LAST_COMMAND == 128 ]; then
-			PS1+="Invalid argument to exit"
-		elif [ $LAST_COMMAND == 129 ]; then
-			PS1+="Fatal error signal 1"
-		elif [ $LAST_COMMAND == 130 ]; then
-			PS1+="Script terminated by Control-C"
-		elif [ $LAST_COMMAND == 131 ]; then
-			PS1+="Fatal error signal 3"
-		elif [ $LAST_COMMAND == 132 ]; then
-			PS1+="Fatal error signal 4"
-		elif [ $LAST_COMMAND == 133 ]; then
-			PS1+="Fatal error signal 5"
-		elif [ $LAST_COMMAND == 134 ]; then
-			PS1+="Fatal error signal 6"
-		elif [ $LAST_COMMAND == 135 ]; then
-			PS1+="Fatal error signal 7"
-		elif [ $LAST_COMMAND == 136 ]; then
-			PS1+="Fatal error signal 8"
-		elif [ $LAST_COMMAND == 137 ]; then
-			PS1+="Fatal error signal 9"
-		elif [ $LAST_COMMAND -gt 255 ]; then
-			PS1+="Exit status out of range"
-		else
-			PS1+="Unknown error code"
-		fi
-		PS1+="\[${DARKGRAY}\])\[${NOCOLOR}\]\n"
-	else
-		PS1=""
-	fi
-	
-	# Weather forcast on top of PS1
-	# \n is used to insert a new line.
-	# \u is the username.
-	# \h is the hostname.
-	# \w is the current working directory.
-	# \$ is the default prompt symbol ($ for normal users and # for root).
-	function weather_prompt {
-    weather_info=$(ansiweather -l Chania)
-    PS1+="\n$weather_info\n "
+    # Function to get the current Git branch and status
+    function git_prompt {
+    local branch status=""
+    if branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null); then
+        if ! git diff --quiet --ignore-submodules --cached; then
+            status+="* "  # Staged changes
+        fi
+        if ! git diff --quiet --ignore-submodules; then
+            status+="~ "  # Unstaged changes
+        fi
+        if [[ -n $(git ls-files --others --exclude-standard) ]]; then
+            status+="? "  # Untracked files
+        fi
+        echo "($branch $status)"
+    fi
 }
-#weather_prompt
 
-	# kernel
-	PS1+="\[${LIGHTGREEN}\]$(krnl)"
-	# Date
-	PS1+="\[${DARKGRAY}\](\[${CYAN}\]\$(date +%a) $(date +%b-'%-m')" # Date
-	PS1+="${BLUE} $(date +'%-I':%M:%S%P)\[${DARKGRAY}\])-" # Time
+    # Define colors
+    local LIGHTGRAY="\033[0;37m"
+    local WHITE="\033[1;37m"
+    local BLACK="\033[0;30m"
+    local DARKGRAY="\033[1;30m"
+    local RED="\033[0;31m"
+    local LIGHTRED="\033[1;31m"
+    local GREEN="\033[0;32m"
+    local LIGHTGREEN="\033[1;32m"
+    local BROWN="\033[0;33m"
+    local YELLOW="\033[1;33m"
+    local BLUE="\033[0;34m"
+    local LIGHTBLUE="\033[1;34m"
+    local MAGENTA="\033[0;35m"
+    local LIGHTMAGENTA="\033[1;35m"
+    local CYAN="\033[0;36m"
+    local LIGHTCYAN="\033[1;36m"
+    local NOCOLOR="\033[0m"
 
-	# CPU
-	PS1+="(\[${MAGENTA}\]CPU $(cpu)%"
+    # Show error exit code if there is one
+    if [[ $LAST_COMMAND != 0 ]]; then
+        PS1="\[${DARKGRAY}\](\[${LIGHTRED}\]ERROR\[${DARKGRAY}\])-(\[${RED}\]Exit Code \[${LIGHTRED}\]${LAST_COMMAND}\[${DARKGRAY}\])-(\[${RED}\]"
+        PS1+="Unknown error code"
+        PS1+="\[${DARKGRAY}\])\[${NOCOLOR}\]\n"
+    else
+        PS1=""
+    fi
 
-	# Jobs
-#	PS1+="\[${DARKGRAY}\]:\[${MAGENTA}\]\j"
+    # Kernel and Date/Time
+    PS1+="\[${LIGHTGREEN}\]$(krnl)"
+    PS1+="\[${DARKGRAY}\](\[${CYAN}\]$(date +%a) $(date +%b-'%-m')"
+    PS1+="${BLUE} $(date +'%-I':%M:%S%P)\[${DARKGRAY}\])-"
 
-	# Network Connections (for a server - comment out for non-server)
-	PS1+="\[${DARKGRAY}\]:\[${MAGENTA}\]Net $(awk 'END {print NR}' /proc/net/tcp)"
+    # CPU and Network
+    PS1+="(\[${MAGENTA}\]CPU $(cpu)%"
+    PS1+="\[${DARKGRAY}\]:\[${MAGENTA}\]Net $(awk 'END {print NR}' /proc/net/tcp)"
+    PS1+="\[${DARKGRAY}\])-"
 
-	PS1+="\[${DARKGRAY}\])-"
+    # User and server
+    local SSH_IP=`echo $SSH_CLIENT | awk '{ print $1 }'`
+    local SSH2_IP=`echo $SSH2_CLIENT | awk '{ print $1 }'`
+    if [ $SSH2_IP ] || [ $SSH_IP ] ; then
+        PS1+="(\[${RED}\]\u@\h"
+    else
+        PS1+="(\[${RED}\]\u"
+    fi
 
-	# User and server
-	local SSH_IP=`echo $SSH_CLIENT | awk '{ print $1 }'`
-	local SSH2_IP=`echo $SSH2_CLIENT | awk '{ print $1 }'`
-	if [ $SSH2_IP ] || [ $SSH_IP ] ; then
-		PS1+="(\[${RED}\]\u@\h"
-	else
-		PS1+="(\[${RED}\]\u"
-	fi
+    # Current directory
+    PS1+="\[${DARKGRAY}\]:\[${BROWN}\]\w\[${DARKGRAY}\])-"
 
-	# Current directory
-	PS1+="\[${DARKGRAY}\]:\[${BROWN}\]\w\[${DARKGRAY}\])-"
+    # Total size of files in current directory
+    PS1+="(\[${GREEN}\]$(/bin/ls -lah | /bin/grep -m 1 total | /bin/sed 's/total //')\[${DARKGRAY}\]:"
 
-	# Total size of files in current directory
-	PS1+="(\[${GREEN}\]$(/bin/ls -lah | /bin/grep -m 1 total | /bin/sed 's/total //')\[${DARKGRAY}\]:"
+    # Number of files
+    PS1+="\[${GREEN}\]$(/bin/ls -A -1 | /usr/bin/wc -l)\[${DARKGRAY}\])"
 
-	# Number of files
-	PS1+="\[${GREEN}\]\$(/bin/ls -A -1 | /usr/bin/wc -l)\[${DARKGRAY}\])"
+    # Git branch and status
+    PS1+="\[${LIGHTBLUE}\]$(git_prompt)\[${DARKGRAY}\]"
 
-	# Skip to the next line
-	PS1+="\n"
+    # Skip to the next line
+    PS1+="\n"
 
-	if [[ $EUID -ne 0 ]]; then
-		PS1+="\[${GREEN}\]>\[${NOCOLOR}\] " # Normal user
-	else
-		PS1+="\[${RED}\]>\[${NOCOLOR}\] " # Root user
-	fi
+    if [[ $EUID -ne 0 ]]; then
+        PS1+="\[${GREEN}\]>\[${NOCOLOR}\] " # Normal user
+    else
+        PS1+="\[${RED}\]>\[${NOCOLOR}\] " # Root user
+    fi
 
-	# PS2 is used to continue a command using the \ character
-	PS2="\[${DARKGRAY}\]>\[${NOCOLOR}\] "
-
-	# PS3 is used to enter a number choice in a script
-	PS3='Please enter a number from above list: '
-
-	# PS4 is used for tracing a script in debug mode
-	PS4='\[${DARKGRAY}\]+\[${NOCOLOR}\] '
+    # Set the final prompt
+    export PS1
 }
 PROMPT_COMMAND='__setprompt'
+
 
 
 
